trigger:
  batch: true
  branches:
    include:
    - master

pr:
  autoCancel: true
  branches:
    include:
    - master

resources:
  repositories:
  - repository: templates
    type: github
    name: brace-rs/azure-ci
    endpoint: brace-rs

stages:
- template: ci/stage-all.yml@templates
  parameters:
    toolchain: file
